/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AdminResult = { 'error' : string } |
  { 'success' : null };
export interface GameDetails {
  'genre' : string,
  'platforms' : string,
  'releaseDate' : string,
}
export type UpdateContentResult = { 'notAdmin' : null } |
  { 'success' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'disablePasswordProtection' : ActorMethod<[], AdminResult>,
  'enablePasswordProtection' : ActorMethod<[string], AdminResult>,
  'getAboutText' : ActorMethod<[], string>,
  'getAdminStatus' : ActorMethod<[], boolean>,
  'getBodyTextColor' : ActorMethod<[], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDeveloperLink' : ActorMethod<[], string>,
  'getFeatures' : ActorMethod<[], Array<string>>,
  'getGameDetails' : ActorMethod<[], GameDetails>,
  'getGameTitle' : ActorMethod<[], string>,
  'getInstagramLink' : ActorMethod<[], string>,
  'getPressEmail' : ActorMethod<[], string>,
  'getTagline' : ActorMethod<[], string>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAdmin' : ActorMethod<[string, string], AdminResult>,
  'isAdmin' : ActorMethod<[Principal], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateAboutText' : ActorMethod<[string], UpdateContentResult>,
  'updateBodyTextColor' : ActorMethod<[string], UpdateContentResult>,
  'updateDeveloperLink' : ActorMethod<[string], UpdateContentResult>,
  'updateFeatures' : ActorMethod<[Array<string>], UpdateContentResult>,
  'updateGameDetails' : ActorMethod<
    [string, string, string],
    UpdateContentResult
  >,
  'updateGameTitle' : ActorMethod<[string], UpdateContentResult>,
  'updateInstagramLink' : ActorMethod<[string], UpdateContentResult>,
  'updatePressEmail' : ActorMethod<[string], UpdateContentResult>,
  'updateTagline' : ActorMethod<[string], UpdateContentResult>,
  'verifyPassword' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];