/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AdminResult = IDL.Variant({
  'error' : IDL.Text,
  'success' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const GameDetails = IDL.Record({
  'genre' : IDL.Text,
  'platforms' : IDL.Text,
  'releaseDate' : IDL.Text,
});
export const UpdateContentResult = IDL.Variant({
  'notAdmin' : IDL.Null,
  'success' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'disablePasswordProtection' : IDL.Func([], [AdminResult], []),
  'enablePasswordProtection' : IDL.Func([IDL.Text], [AdminResult], []),
  'getAboutText' : IDL.Func([], [IDL.Text], ['query']),
  'getAdminStatus' : IDL.Func([], [IDL.Bool], ['query']),
  'getBodyTextColor' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDeveloperLink' : IDL.Func([], [IDL.Text], ['query']),
  'getFeatures' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getGameDetails' : IDL.Func([], [GameDetails], ['query']),
  'getGameTitle' : IDL.Func([], [IDL.Text], ['query']),
  'getInstagramLink' : IDL.Func([], [IDL.Text], ['query']),
  'getPressEmail' : IDL.Func([], [IDL.Text], ['query']),
  'getTagline' : IDL.Func([], [IDL.Text], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAdmin' : IDL.Func([IDL.Text, IDL.Text], [AdminResult], []),
  'isAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateAboutText' : IDL.Func([IDL.Text], [UpdateContentResult], []),
  'updateBodyTextColor' : IDL.Func([IDL.Text], [UpdateContentResult], []),
  'updateDeveloperLink' : IDL.Func([IDL.Text], [UpdateContentResult], []),
  'updateFeatures' : IDL.Func([IDL.Vec(IDL.Text)], [UpdateContentResult], []),
  'updateGameDetails' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [UpdateContentResult],
      [],
    ),
  'updateGameTitle' : IDL.Func([IDL.Text], [UpdateContentResult], []),
  'updateInstagramLink' : IDL.Func([IDL.Text], [UpdateContentResult], []),
  'updatePressEmail' : IDL.Func([IDL.Text], [UpdateContentResult], []),
  'updateTagline' : IDL.Func([IDL.Text], [UpdateContentResult], []),
  'verifyPassword' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AdminResult = IDL.Variant({ 'error' : IDL.Text, 'success' : IDL.Null });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const GameDetails = IDL.Record({
    'genre' : IDL.Text,
    'platforms' : IDL.Text,
    'releaseDate' : IDL.Text,
  });
  const UpdateContentResult = IDL.Variant({
    'notAdmin' : IDL.Null,
    'success' : IDL.Null,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'disablePasswordProtection' : IDL.Func([], [AdminResult], []),
    'enablePasswordProtection' : IDL.Func([IDL.Text], [AdminResult], []),
    'getAboutText' : IDL.Func([], [IDL.Text], ['query']),
    'getAdminStatus' : IDL.Func([], [IDL.Bool], ['query']),
    'getBodyTextColor' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDeveloperLink' : IDL.Func([], [IDL.Text], ['query']),
    'getFeatures' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getGameDetails' : IDL.Func([], [GameDetails], ['query']),
    'getGameTitle' : IDL.Func([], [IDL.Text], ['query']),
    'getInstagramLink' : IDL.Func([], [IDL.Text], ['query']),
    'getPressEmail' : IDL.Func([], [IDL.Text], ['query']),
    'getTagline' : IDL.Func([], [IDL.Text], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAdmin' : IDL.Func([IDL.Text, IDL.Text], [AdminResult], []),
    'isAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateAboutText' : IDL.Func([IDL.Text], [UpdateContentResult], []),
    'updateBodyTextColor' : IDL.Func([IDL.Text], [UpdateContentResult], []),
    'updateDeveloperLink' : IDL.Func([IDL.Text], [UpdateContentResult], []),
    'updateFeatures' : IDL.Func([IDL.Vec(IDL.Text)], [UpdateContentResult], []),
    'updateGameDetails' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [UpdateContentResult],
        [],
      ),
    'updateGameTitle' : IDL.Func([IDL.Text], [UpdateContentResult], []),
    'updateInstagramLink' : IDL.Func([IDL.Text], [UpdateContentResult], []),
    'updatePressEmail' : IDL.Func([IDL.Text], [UpdateContentResult], []),
    'updateTagline' : IDL.Func([IDL.Text], [UpdateContentResult], []),
    'verifyPassword' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };